name: inorbit

services:
  # api:
  #   container_name: inorbit_api
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.dev
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env.development
  #   volumes:
  #     - .:/app:cached
  #     - /app/node_modules
  #   command: sh -c "yarn prisma migrate dev && yarn start:dev"
  #   depends_on:
  #     - pg
  #   networks:
  #     - inorbit_network

  pg:
    container_name: inorbit_pg
    image: postgres:17
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    volumes:
      - ./docker/volumes:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - inorbit_network

networks:
  inorbit_network:
    driver: bridge
